class_views/urls.py
from django.urls import path
from .views import NewView, TutorCreate, TutorList, TutorDetail, TutorUpdate, TutorDeleteView

app_name = 'class_views'

urlpatterns = [
    path('about/', NewView.as_view(), name='about'),
    path('tutor/create/', TutorCreate.as_view(), name='tutor-create'),
    path('tutor/list/', TutorList.as_view(), name='tutor-list'),
    path('tutor/<int:pk>/', TutorDetail.as_view(), name='tutor-detail'),
    path('tutor/<int:pk>/update/', TutorUpdate.as_view(), name='tutor-update'),
    path('tutor/<int:pk>/delete/', TutorDeleteView.as_view(), name='tutor-delete')
    # other paths
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from myapp import views
 
urlpatterns = [
    path('admin/', admin.site.urls),
    # paths for myapp
    path("hello/", views.hello),
    path('index/', views.index),
    path('show/', views.show),
    path('ssession', views.setsession),
    path('gsession', views.getsession),
    path('scookie', views.setcookie),
    path('gcookie', views.getcookie),   
    path('csv', views.getfile), #adding csv url
    path('pdf', views.getpdf),    # adding pdf url
    path('mail', views.mail),
    
    # path for classviews app
    path('', include(('class_views.urls'), namespace='class_views'))
]

class_views/models.py
from django.db import models

# Create your models here.

# creating a database table/model
class Tutor(models.Model):
    first_name  = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    mobile = models.CharField(max_length=10)
    email = models.EmailField()
    
    def __str__(self):
        return "%s %s" %(self.first_name, self.last_name)

myapp/models.py
from __future__ import unicode_literals
from django.db import models



# Create your models here.

class Student(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    contact = models.IntegerField()
    email = models.EmailField(max_length=50)
    age = models.IntegerField()
    
    
    class Meta:
        db_table = 'student'


class Employee(models.Model):
    emp_id = models.IntegerField()
    emp_name = models.CharField(max_length=20)
    emp_contact = models.IntegerField()
    
    class Meta:
        db_table = 'employee'

class_views/forms.py
from django.forms import fields
from class_views.models import Tutor
from django import forms 

class TutorForm(forms.ModelForm):
    
    class Meta:
        model = Tutor       # specifying the model to use
        fields = "__all__"      # applying all fields
        
        

class_views/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View 

from .models import Tutor
from .forms import TutorForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView        # to create an instance of a table;  to update a particluar instance of the table in a database
from django.views.generic.list import ListView   # to display multiple instances of a table in a databases
from django.views.generic.detail import DetailView  # to display specific instance of a table in a database     

from django.urls import reverse_lazy, reverse
# Create your views here.

# creating a class based view
class NewView(View):
    def get(self, request):
        # TODO -- add view logic
        return HttpResponse('reponse')
    
    
# using CreateView
class TutorCreate(CreateView):
    model = Tutor
    fields = '__all__'
    success_url = reverse_lazy('class_views:tutor-list')
    template_name = 'class_views/tutor_form.html'
    
# to list all instances of the table
class TutorList(ListView):
    model = Tutor
    success_url = reverse_lazy('class_views:tutor-list')
    template_name = 'class_views/tutor_list.html'

# to list a specific instace of the table 
class TutorDetail(DetailView):
    model = Tutor
    success_url = reverse_lazy('class_views:tutor-list')
    template_name = 'class_views/tutor_detail.html'
    
class TutorUpdate(UpdateView):
    model = Tutor
    fields = '__all__'
    template_name_suffix = "_update_form"
    success_url = reverse_lazy('class_views:tutor-list')
    template_name = 'class_views/tutor_form.html'
    
class TutorDeleteView(DeleteView):
    model = Tutor
    success_url = reverse_lazy('class_views:tutor-list')
    template_name = 'class_views/tutor_confirm_delete.html'

myapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseNotFound
import datetime
from django.template import loader
from django.views.decorators.http import require_http_methods
from myapp.form import StudForm, EmpForm
from myapp.functions.functions import handle_uploaded_file
from django.contrib.sessions.models import Session
import csv
from myapp.models import Employee
from reportlab.pdfgen import canvas
from mysite import settings
from django.core.mail import send_mail
# Create your views here.
# creating my views

# function to send a mail
def mail(request):
    subject = "Greetings"
    msg = "Abraham sent sent you a mail. Learning Django is fun."
    to = "abkc070@gmail.com"
    res = send_mail(subject, msg, settings.EMAIL_HOST_USER, [to])
    if(res == 1):
        msg = "Mail Sent Successfully"
    else:
        msg = "Mail could not sent"
    return HttpResponse(msg)

def getpdf(request):
    response = HttpResponse(content_type='application/pdf')  # MIME(content)
    response['Content-Disposition'] = 'attatchment;filename="myapp.pdf"'  # setting filename
    
    p = canvas.Canvas(response)
    p.setFont("Times-Roman", 55)
    p.drawString(100,700,"Hello, Abraham.")
    p.showPage()
    p.save()
    
    return response
    




@require_http_methods(["GET","POST"])
def hello(request):
    return HttpResponse("<h2>Hello, Welcom to MySite!</h2>")

 

def show(request):
    return HttpResponse('<h1>This is Http GET request</h1>')


# form validation
def stud(request):
    # checking wether the request is post or not
    if request.method == "POST":
        form = StudForm(request.POST)
        # form inputs is valid
        if form.is_valid():
            try:
                return redirect('/')
            except:
                pass
            
        else:
            form = StudForm()
        return render(request, 'index.html', {'form':form })
    
    
def emp(request):
    if request.method == 'POST':
        form = EmpForm(request.POST)
        
        if form.is_valid():
            try:
                return('/')
            except:
                pass
        else:
            form = EmpForm()
        return render(request,'index2.html',{'form':form} )
    
    
    
def index(request):
    if request.method == "POST":
        student = StudForm(request.POST, request.FILES)
        
        if student.is_valid():
            handle_uploaded_file(request.FILES['file'])
            return HttpResponse("File uploaded successfully")
    else:
        student = StudForm()
        return render(request, "index.html", {'form': student})
    

def index(request):
    if request.method == "POST":
        student = StudForm(request.POST, request.FILES)
        
        if student.is_valid():
            handle_uploaded_file(request.FILES['file'])
            return HttpResponse("File uploaded successfully")
    else:
        student = StudForm()
        return render(request, "index.html", {'form': student})
    
    
        #when using the student database in models.py
    #stu = StudForm()
    #return render(request, 'index.html', {'form':stu })
    
# sessions
def setsession(request):
    request.session['sname'] = 'Abraham'
    request.session['semail'] = 'abkc@gmail.com'
    return HttpResponse('session is set')

def getsession(request):
    studentname = request.session['sname']
    studentemail = request.session['semail']
    return HttpResponse(studentname + " " + studentemail)
    
    
# cookies
def setcookie(request):
    response = HttpResponse("Cookies set")
    response.set_cookie('django-tutorial', "Django Cookies")
    return response

def getcookie(request):
    tutorial = request.COOKIES['django-tutorial']
    return HttpResponse('django tutorials @:' + tutorial)


# csv getfile
def getfile(request):
    response = HttpResponse(content_type= 'text/csv')
    response['Content-Disposition'] = 'attatchment; filename="file.csv"'
    
    # a dynamic csv using database
    employees = Employee.objects.all()
    writer = csv.writer(response)
    for employee in employees:
        writer.writerow([employee.emp_id, employee.emp_name,employee.emp_contact])
    return response
    
    #for static csv
    #writer = csv.writer(response)
    #writer.writerow(['1001','Joel','Andoh','MA'])
    #writer.writerow(['1002', 'Jonathan','Ohene', 'EL'])
    #return response

class_views/templates/class_views/base.html
<!doctype html>  
<html lang="en">  
  <head>  
    <!-- Required meta tags -->  
    <meta charset="utf-8">  
    <meta name="viewport" content="width=device-width, initial-scale=1">  
  
    <!-- Bootstrap CSS -->    
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}"/>
    <script src="{% static '/js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
    <title>Register Page</title>  
  </head>  
  <body>  
  <div class = 'col-md-8'>  
     {% if messages %}  
        <ul>   
            {% for message in messages %}  
              <div class = 'alert alert-{{message.tags}}'>  
                {{ message }}   
              </div>  
              {% endfor %}  
        </ul>   
    {% endif %}   
  </div>  
  {% block content %}  
    <scriptjs/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>  
  
      
    {% endblock content %}  
  </body>  
</html>  

class_views/templates/class_views/tutor_confirm_delete.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Tutor Detail</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"/>
    <script src="{% static '/js/bootstrap.js' %}" type="text/javascript"></script>
</head>
<body>
    <h1>Confirm Delete</h1>
    <p>Are you sure you want to delete this tutor?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Yes, delete</button>
    </form>
</body>
</html>
 

class_views/templates/class_views/tutor_detail.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Tutor Detail</title>
</head>
<body>
	 <!-- delete.html -->
  <h1>Delete Tutor</h1>

  <p>Are you sure you want to delete this tutor?</p>
  <p><strong>Name:</strong> {{ tutor.name }}</p>
  <p><strong>Subject:</strong> {{ tutor.subject }}</p>
  <p><strong>Email:</strong> {{ tutor.email }}</p>
  <p><strong>Phone:</strong> {{ tutor.phone }}</p>

  <form method="POST">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Delete</button>
    <a href="{% url 'tutor-list' %}" class="btn btn-secondary">Cancel</a>
  </form>

</body>
</html>

class_views/templates/class_views/tutor_form.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Tutors Form</title>
        {% load static %}
        <!--using styles and scripts-->
        <link href="{% static '/css/styles.css' %}" rel="stylesheet">
        <script src="{% static '/js/script.js' %}" type="text/javascript"></script>
    </head>
    <body>
        <form method="POST" class="post-form" enctype="multipart/form-data">
            <!--creating a form with help the databaase-->
            {% csrf_token %}
            {{ form.as_p}}
                <button type="submit" class="save btn btn-default">Save</button>
        </form>
    </body>
</html>

class_views/templates/class_views/tutor_list.html
<!-- class_views/templates/class_views/tutor_detail.html -->

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Tutor Detail</title>
    {% load static %}
    <link rel="stylesheet" href="{% static '/css/bootstrap.css' %}"/>
    <script src="{% static '/js/bootstrap.js' %}" type="text/javascript"></script>
</head>
<body>
    {% csrf_token %}
    <table class="table table-borderless">  
        <thead class="border-bottom font-weight-bold">  
            <tr>  
                <td>First Name</td>  
                <td>Last Name</td>  
                <td>Mobile</td>  
                <td>Email</td>  
                    <a href="{% url 'class_views:tutor-create' %}" class="btn btn-outline-success">  
                        <i class="fas fa-plus"></i> Add New  
                    </a>  
                </td>  
            </tr>  
        </thead>  
      
        {% for object in object_list %}  
            <!-- Display Objects -->  
            <tr>  
                    <td>{{ object.first_name }}</td>  
                    <td> {{object.last_name }}</td>  
                    <td> {{object.mobile }}</td>  
                    <td>{{object.email }} </td>  
      
                <td>  
                <td><button><a href="{% url 'class_views:tutor-delete' pk=object.pk %}"  class = 'class="btn text-secondary px-0'> Delete  
                </a></button></td>  
      
                <td><button><a  href="{% url 'class_views:tutor-update' pk=object.pk %}" class = 'class="btn text-secondary px-0'> Update  
                </a></button></td>  
        {% endfor %}  
      
    </table>  
</body>
</html>

myapp/templates/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Index</title>
        {% load static %}
        <!--using styles and scripts-->
        <script src="{% static '/js/script.js' %}" type="text/javascript"></script>
        <link href="{% static '/css/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h1>Welcome to Django!!!</h1>
        <h3>My Name is: {{student}}</h3>
        <!--add an image-->
        <img 
            src="{% static '/img1.jpeg' %}" alt="My image" height="300px" width="700px"
        >
        <form method="POST" class="post-form" enctype="multipart/form-data">
            <!--creating a form with help the databaase-->
            {% csrf_token %}
            {{ form.as_p}}
                <button type="submit" class="save btn btn-default">Save</button>
        </form>
    </body>
</html>

myapp/templates/index2.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Index</title>
        {% load static %}
        <!--using styles and scripts-->
        <script src="{% static '/js/script.js' %}" type="text/javascript"></script>
        <link href="{% static '/css/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h1>Welcome to Django!!!</h1>
        <h3>My Name is: {{student}}</h3>
        <!--add an image-->
        <img 
            src="{% static '/forest.jpeg %}" alt="forest" height="300px" width="700px"
        >
        <form method="POST" class="post-form" enctype="multipart/form-data">
            <!--creating a form with help the databaase-->
            {% csrf_token %}
            {{ form.as_p}}
                <button type="submit" class="save btn btn-default">Save</button>
        </form>
    </body>
</html>